# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14ef13312e2275e0284dda56c9bbfb4d3d5196a05ee24c68e39cc6c82e3b218e775d92ed40d9735024e68b07d7713c60224594ee7ca0e2d331324c987a6812f1

test:
  secret_key_base: 41d6d34ac609fbb5b79bdfe1af49db61432d52056606098a82ddc1f272f2b4c054d2d8ba953844efca5a0056511c0791f360751079e91fdba8f22cbb86ca93ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
